# 相关配置说明
  # favicon: 网站图标
  # avatar: 主题用户头像与昵称
  # rss: rss订阅
  # gtag: Google 分析
  # comments: 文章评论系统
    # gitalk
    # disqus
  # navbar: 主题页面导航栏
  # catalog: 文章目录
  # friends: 友链
  # footer: 页脚信息

# enable: 是否开启相应功能，可选true & false

# 网站图标
favicon:
  enable: true
  icon: /images/favicon.ico
  touch_icon: /images/favicon.ico

# 主题用户头像与昵称
avatar:
  author_photo: /images/34339465.jpg
  author_nickname: Oranges

# Google 分析
gtag:
  enable: false
  gtagkey:

# 文章评论系统
comments:
  enable: true
  # 目前支持gitalk与disqus评论，选择喜欢的一种开启即可
  gitalk:
    enable: false
    clientID:
    clientSecret:
    repo:
    owner:
    admin:
    distractionFreeMode: false

  # disqus 需科学上网方可使用
  disqus:
    # https://disqus.com/
    # 注册账号，获取shortname.disqus.com，shortname为你定义的唯一name
    # 举个例子：我注册配置完毕后的网址为zcheng.disqus.com，将zcheng填入即可
    enable: true
    shortname: zcheng

# 主题页面导航栏
navbar:
  -
    name: 主页
    enable: true
    path: /
  -
    name: 归档
    enable: true
    path: /archives/
  -
    name: 标签
    enable: true
    path: /tags/
  -
    name: 朋友
    enable: true
    path: /friends/
  -
    name: 关于我
    enable: true
    path: /about/

# 文章目录
catalog:
  enable: true

# 友链
friends:
  # nickname: 昵称
  # site: 地址
  # meta: 描述
  -
    nickname: Lxwu
    site: https://lxwu.me/
    meta:
  -
    nickname: Mhyu
    site: https://mhyu.top/
    meta:

# 页脚信息
footer:
  # social: 社交方式
  # more: 更多页脚信息
  social:
    # name: 名称
    # icon: 图标，目前仅支持IconFont部分图标
    # path: 地址
    -
      name: github
      icon: github
      path: https://github.com/zchengsite/
    -
      name: rss
      icon: rss
      path: atom.xml

  more:
    -
      name: Copyright © Oranges 2020
      path: https://github.com/zchengsite/hexo-theme-oranges
    -
      name: 鄂ICP备18028045号
      path: http://www.beian.miit.gov.cn
